// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prefer DIRECT_URL, fall back to DATABASE_URL. Throw a clear error if neither is set.
const directUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
if (!directUrl) {
  throw new Error(
    "PrismaConfigEnvError: Missing required environment variable: DIRECT_URL or DATABASE_URL"
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
      seed: 'tsx prisma/seed.ts'
  },
  datasource: {
    url: directUrl,
  },
});
